### PR TITLE
Update Git commands

### PR DESCRIPTION
**Pull request by GuilhermeVBeira**
Update git commands to stop show warnings and deprecated commands
image
image
image
image
image

### CODE REVIEW

**Review by avelino — APPROVED** [review]
LGTM

**Comment by cassiobotaro** [comment]
@GuilhermeVBeira Can you update PR with other deprecations? https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L610

**Comment by cassiobotaro** [comment]
@GuilhermeVBeira Can you update Gdiff too? https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L610

**Comment by GuilhermeVBeira** [comment]
> @GuilhermeVBeira Can you update Gvdiff too? https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L610

Sure @cassiobotaro

**Review by cassiobotaro — APPROVED** [review]

**Comment by cassiobotaro** [comment]
Thanks @GuilhermeVBeira !

**Pull request merged**
