### PR TITLE
Updating Rust default configuration to become Vim as Rust IDE.

### PR DESCRIPTION
**Pull request by GiovanniSM20**
I use vim-bootstrap for some time and decided to contribute to the project today, I saw a failure in README.md regarding dependency and I follow the [RLS project](http://rls.booyaa.wtf/) which shows a list of [dependencies to Vim8 to make Vim an IDE.](http://rls.booyaa.wtf/#vim8)

There is also missing the addition of another block to the configuration but I could not find it to solve.

```
if executable('rls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'rls',
        \ 'cmd': {server_info->['rustup', 'run', 'nightly', 'rls']},
        \ 'whitelist': ['rust'],
        \ })
endif 
```

Neovim also has a [setting.](http://rls.booyaa.wtf/#neovim)

### CODE REVIEW

**Comment by GiovanniSM20** [comment]
I think a good place to track "legal" dependencies to add on Vim is :
https://areweideyet.com/

**Comment by avelino** [comment]
@marioidival help on review Mr. Rust

**Comment by lerrua** [comment]
@GiovanniSM20 thanks a lot for the PR. I've used `deoplete` in my local vimrc, works well with my python, go and rust bundle. Maybe we can try it or help me and tell me if your config is better than this.

```
" my bundles

" autocomplete for python
Plug 'zchee/deoplete-jedi'
" Go
Plug 'zchee/deoplete-go', { 'do': 'make'}
" Rust
Plug 'sebastianmarkow/deoplete-rust'

" deoplete
let g:deoplete#enable_at_startup = 1

" Rust
let g:racer_cmd = "$HOME/.cargo/bin/racer"
" let g:deoplete#sources#rust#racer_binary="$HOME/.cargo/bin/racer"
let g:deoplete#sources#rust#racer_binary='/home/leroy/.cargo/bin/racer'
let g:deoplete#sources#rust#rust_source_path="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
let g:deoplete#sources#rust#documentation_max_height=20

augroup rust-mapping
    autocmd!
    autocmd filetype rust nmap <buffer> gd <Plug>DeopleteRustGoToDefinitionTab
    autocmd filetype rust nmap <buffer> K <plug>DeopleteRustShowDocumentation
augroup end
```

I like that way because I have the same features for rust, go and python autocomplete, docs and go to definition features.
But, to be honest I never tried Asyncomplete.vim and I don't know if this will fit with my stack. I'll take some days to test it. :)

**Comment by qmx** [comment]
@GiovanniSM20 you might want to take a look at https://github.com/w0rp/ale - it has been by far the best LSP client I've used on vim.

**Comment by GiovanniSM20** [comment]
eu o conheço @qmx ;)

**Comment by andys8** [comment]
Ale is part of the [template](https://github.com/avelino/vim-bootstrap/blob/fd652d594beb82f03d368b9c12cfd58edf6cc561/vim_template/vimrc#L41) and [has support for the `rls` language server](https://github.com/dense-analysis/ale/blob/73812c3e41c1c7fcf1705811f35ac4c9ccec003e/doc/ale-rust.txt#L22). Although I don't know how it compares to this approach.

**Pull request merged**
